# Generated by Django 5.0.1 on 2024-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestschedule', '0002_alter_requestschedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
