# Generated by Django 5.0.1 on 2024-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestschedule', '0003_requestschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestschedule',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
