# Generated by Django 5.0.1 on 2024-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestschedule', '0004_alter_requestschedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgetdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
