# Generated by Django 5.0.1 on 2024-01-30 06:32

import django.db.models.deletion
import estimateproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimateproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectType', models.CharField(blank=True, max_length=100, null=True)),
                ('yourRole', models.CharField(blank=True, max_length=100, null=True)),
                ('servicesNeeded', models.CharField(blank=True, max_length=100, null=True)),
                ('preferredContactTime', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(default=None, max_length=250, null=True, upload_to=estimateproject.models.directory_path)),
                ('attachmentname', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('projectDetails', models.CharField(blank=True, max_length=100, null=True)),
                ('newsletterSubscription', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=True)),
                ('estimateProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimateproject.estimateproject')),
            ],
        ),
        migrations.CreateModel(
            name='Alreadyhave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=True)),
                ('estimateProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimateproject.estimateproject')),
            ],
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=100)),
                ('value', models.BooleanField(default=True)),
                ('estimateProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimateproject.estimateproject')),
            ],
        ),
        migrations.AddField(
            model_name='estimateproject',
            name='userDetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimateproject.userdetails'),
        ),
    ]
